apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-buddy
spec:
  selector:
    matchLabels:
      app: board-buddy
  replicas: 1
  template:
    metadata:
      labels:
        app: board-buddy
    spec:
      containers:
        - name: board-buddy
          envFrom:
          - secretRef:
              name: board-buddy-env
          image: benjaminpknox/boardbuddy:db18acd
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: board-buddy-service
spec:
  selector:
    app: board-buddy
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: board-buddy-ingress
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  tls:
  - hosts:
    - board-buddy.local.cloud
    secretName: board-buddy-tls-secret
  rules:
    - host: "board-buddy.local.cloud"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: board-buddy-service
                port:
                  number: 3000
